name: Tests for INSO repository
run-name: ${{ github.actor }} is executing the tests
on: [push]
jobs:
  test:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout repo with tests
        uses: actions/checkout@v4
        with:
          repository: ualinso/2324-tests
          path: 2324-tests

      - name: Test execution
        working-directory: ./2324-tests/inso2324
        run: mvn test

      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "**/surefire-reports/TEST-*.xml"
        if: always()
